import assert from 'node:assert/strict';
import {readFile,readdir} from 'node:fs/promises';
import test from 'node:test';
import CommunicationMessage from '../arcane/entities/CommunicationMessage.js';
import CommunicationThread from '../arcane/entities/CommunicationThread.js';
import CommunicationProviderRegistry from '../arcane/modules/CommunicationProviderRegistry.js';
import ArcaneCommunicationBridge from '../arcane/modules/ArcaneCommunicationBridge.js';
import InMemoryCommunicationProvider from '../arcane/modules/InMemoryCommunicationProvider.js';
import {assessScamRisk} from '../arcane/modules/ScamRiskPolicy.js';
import CommunicationHub from '../arcane/modules/CommunicationHub.js';
import {inspectMessageRecords,normalizeContentAdvisory} from '../arcane/modules/MessageAdvisory.js';

const read=relative=>readFile(new URL(`../${relative}`,import.meta.url),'utf8');
const provider={id:'test-provider',label:'Test provider',channels:['sms'],async listThreads(){return []},async getMessages(){return []},async send(value){return value}};

test('communication records preserve provider and channel identity',()=>{const message=new CommunicationMessage({id:'m1',threadId:'t1',providerId:'phone',channel:'sms',body:'Hello',timestamp:'2026-07-13T12:00:00Z',unread:true});const thread=new CommunicationThread({id:'t1',providerId:'phone',channel:'sms',title:'Jordan',updatedAt:message.timestamp,messages:[message]});assert.equal(thread.messages[0].providerId,'phone');assert.equal(thread.channel,'sms');assert.equal(message.status,'received');assert.throws(()=>new CommunicationMessage({}),/required/)});
test('provider registry requires and preserves the neutral provider contract',async()=>{const registry=new CommunicationProviderRegistry([provider]),stored=registry.get('test-provider');assert.equal(stored.label,'Test provider');assert.equal(typeof stored.listThreads,'function');assert.deepEqual(await stored.listThreads(),[]);assert.throws(()=>registry.register({id:'broken'}),/listThreads/);assert.throws(()=>registry.register(provider),/already registered/)});
test('bridge normalizes list and send records without embedding credentials',async()=>{const requests=[];const bridge=new ArcaneCommunicationBridge({id:'phone',channels:['sms'],endpoint:'http://127.0.0.1:8020/',fetchImpl:async(url,options={})=>{requests.push({url,options});return {ok:true,status:200,async text(){return JSON.stringify(url.endsWith('/threads')?{threads:[{id:'t1',channel:'sms',title:'Test',updatedAt:'2026-07-13T12:00:00Z'}]}:{message:{id:'m1',channel:'sms',body:'Sent',timestamp:'2026-07-13T12:01:00Z'}})}}}});const threads=await bridge.listThreads();const sent=await bridge.send({threadId:'t1',body:'Sent'});assert(threads[0] instanceof CommunicationThread);assert(sent instanceof CommunicationMessage);assert.equal(requests[1].options.method,'POST');assert.doesNotMatch(JSON.stringify(requests),/password|authToken|apiSecret/i)});
test('communications components are domain-neutral, accessible, and syntactically valid',async()=>{for(const file of ['unified-inbox.html','conversation-view.html','integration-settings.html']){const html=await read(`arcane/components/${file}`);const script=html.match(/<script type="module">([\s\S]*?)<\/script>/)?.[1];const AsyncFunction=Object.getPrototypeOf(async function(){}).constructor;assert.ok(script,file);assert.doesNotThrow(()=>new AsyncFunction(script),file);assert.doesNotMatch(html,/Arcane Mail|Arcane Messages|Gmail|WhatsApp|Twilio/,file)}});
test('Mail and Messages are thin shells over shared communications capabilities',async()=>{const [mail,messages,mailModule,messagesModule,registry]=await Promise.all([read('apps/mail/index.html'),read('apps/messages/index.html'),read('apps/mail/modules/MailApp.js'),read('apps/messages/modules/MessagesApp.js'),read('machine_bundles/arcane-os-machine-bundle-v0.8.4/arcane-apps.json').then(JSON.parse)]);for(const html of [mail,messages])for(const component of ['unified-inbox','conversation-view','integration-settings','theme-switcher'])assert.match(html,new RegExp(`arcane/components/${component}\\.html`));for(const source of [mailModule,messagesModule]){assert.match(source,/CommunicationAppController/);assert.doesNotMatch(source,/class Communication|innerHTML|fetch\s*\(/)}assert.match(messagesModule,/messages\.google\.com\/web/);assert.match(messagesModule,/defaultEnabled:true/);assert.deepEqual(registry.apps.mail.capabilities,['external.open','network.status.read','preferences.read','preferences.write','appearance.read','appearance.write']);assert.deepEqual(registry.apps.messages.capabilities,registry.apps.mail.capabilities.slice(1));for(const app of ['mail','messages']){const entries=await readdir(new URL(`../apps/${app}`,import.meta.url));assert(!entries.includes('components'));assert(!entries.includes('entities'))}});
test('connection settings do not solicit or persist provider secrets',async()=>{const sources=await Promise.all(['arcane/components/integration-settings.html','arcane/modules/CommunicationPreferences.js','apps/mail/modules/MailApp.js','apps/messages/modules/MessagesApp.js'].map(read));for(const source of sources)assert.doesNotMatch(source,/name=["']?(password|token|secret)|apiKey\s*:|authToken\s*:/i);assert.match(sources[0],/Passwords and API secrets are never stored here/)});
test('in-memory communications provider supplies deterministic demo messages without a network',async()=>{const demo=new InMemoryCommunicationProvider({id:'demo-sms',channels:['sms'],threads:[{id:'t1',channel:'sms',title:'DEMO',updatedAt:'2026-07-18T12:00:00Z'}],messages:{t1:[{id:'m1',channel:'sms',body:'Buy a gift card immediately.',timestamp:'2026-07-18T12:00:00Z'}]}});const threads=await demo.listThreads(),messages=await demo.getMessages('t1');assert.equal(threads[0].providerId,'demo-sms');assert.equal(messages[0].body,'Buy a gift card immediately.');assert.equal(assessScamRisk(messages[0].body).level,'high')});
test('hub preserves class-provider methods for refresh, read, and simulated send',async()=>{const demo=new InMemoryCommunicationProvider({id:'class-demo',channels:['sms'],threads:[{id:'t1',channel:'sms',title:'DEMO',updatedAt:'2026-07-18T12:00:00Z'}],messages:{t1:[{id:'m1',channel:'sms',body:'Hello',timestamp:'2026-07-18T12:00:00Z'}]}}),hub=new CommunicationHub({providers:[demo],enabledProviderIds:['class-demo']});assert.equal((await hub.refresh()).threads.length,1);assert.equal((await hub.messages({id:'t1',providerId:'class-demo',channel:'sms',title:'DEMO',updatedAt:'2026-07-18T12:00:00Z'})).length,1);await hub.send({providerId:'class-demo',threadId:'t1',channel:'sms',body:'Local reply'});assert.equal((await demo.getMessages('t1')).length,2)});
test('message advisories are bounded, object-keyed, and fail visibly',async()=>{const duplicateA={id:'__proto__',body:'one'},duplicateB={id:'__proto__',body:'two'};const {advisories,failures}=await inspectMessageRecords([duplicateA,duplicateB],message=>{if(message===duplicateB)throw new Error('offline');return {level:'critical',title:'x'.repeat(200),summary:'y'.repeat(700),signals:Array(12).fill('z'.repeat(160))}});assert.equal(advisories.size,2);assert.equal(failures,1);assert.equal(advisories.get(duplicateA).title.length,120);assert.equal(advisories.get(duplicateA).summary.length,500);assert.equal(advisories.get(duplicateA).signals.length,8);assert.equal(advisories.get(duplicateB).level,'unavailable');assert.equal(normalizeContentAdvisory(null),null)});
test('Messages injects local Scamurai review into every supported inbound provider',async()=>{const [app,controller,conversation]=await Promise.all([read('apps/messages/modules/MessagesApp.js'),read('arcane/modules/CommunicationAppController.js'),read('arcane/components/conversation-view.html')]);assert.match(app,/scamurai-demo/);assert.match(app,/assessScamRisk/);assert.match(app,/direction!==['"]inbound['"]/);assert.match(app,/\['sms','mms','rcs'\]/);assert.match(controller,/providerFactory/);assert.match(controller,/inspectMessageRecords/);assert.match(controller,/selectionVersion/);assert.match(conversation,/advisories\.get\(item\)/);assert.match(conversation,/advisory\.title/);assert.doesNotMatch(app,/messages\.google\.com.*fetch|querySelector.*messages\.google/i);assert.doesNotMatch(app,/onAdvisoryAction|apps\/scamurai/)});
