import assert from 'node:assert/strict';
import {readFile,readdir} from 'node:fs/promises';
import test from 'node:test';
import CommunicationMessage from '../arcane/entities/CommunicationMessage.js';
import CommunicationThread from '../arcane/entities/CommunicationThread.js';
import CommunicationProviderRegistry from '../arcane/modules/CommunicationProviderRegistry.js';
import ArcaneCommunicationBridge from '../arcane/modules/ArcaneCommunicationBridge.js';

const read=relative=>readFile(new URL(`../${relative}`,import.meta.url),'utf8');
const provider={id:'test-provider',label:'Test provider',channels:['sms'],async listThreads(){return []},async getMessages(){return []},async send(value){return value}};

test('communication records preserve provider and channel identity',()=>{const message=new CommunicationMessage({id:'m1',threadId:'t1',providerId:'phone',channel:'sms',body:'Hello',timestamp:'2026-07-13T12:00:00Z',unread:true});const thread=new CommunicationThread({id:'t1',providerId:'phone',channel:'sms',title:'Jordan',updatedAt:message.timestamp,messages:[message]});assert.equal(thread.messages[0].providerId,'phone');assert.equal(thread.channel,'sms');assert.equal(message.status,'received');assert.throws(()=>new CommunicationMessage({}),/required/)});
test('provider registry requires the neutral provider contract',()=>{const registry=new CommunicationProviderRegistry([provider]);assert.equal(registry.get('test-provider').label,'Test provider');assert.throws(()=>registry.register({id:'broken'}),/listThreads/);assert.throws(()=>registry.register(provider),/already registered/)});
test('bridge normalizes list and send records without embedding credentials',async()=>{const requests=[];const bridge=new ArcaneCommunicationBridge({id:'phone',channels:['sms'],endpoint:'http://127.0.0.1:8020/',fetchImpl:async(url,options={})=>{requests.push({url,options});return {ok:true,status:200,async text(){return JSON.stringify(url.endsWith('/threads')?{threads:[{id:'t1',channel:'sms',title:'Test',updatedAt:'2026-07-13T12:00:00Z'}]}:{message:{id:'m1',channel:'sms',body:'Sent',timestamp:'2026-07-13T12:01:00Z'}})}}}});const threads=await bridge.listThreads();const sent=await bridge.send({threadId:'t1',body:'Sent'});assert(threads[0] instanceof CommunicationThread);assert(sent instanceof CommunicationMessage);assert.equal(requests[1].options.method,'POST');assert.doesNotMatch(JSON.stringify(requests),/password|authToken|apiSecret/i)});
test('communications components are domain-neutral, accessible, and syntactically valid',async()=>{for(const file of ['unified-inbox.html','conversation-view.html','integration-settings.html']){const html=await read(`arcane/components/${file}`);const script=html.match(/<script type="module">([\s\S]*?)<\/script>/)?.[1];const AsyncFunction=Object.getPrototypeOf(async function(){}).constructor;assert.ok(script,file);assert.doesNotThrow(()=>new AsyncFunction(script),file);assert.doesNotMatch(html,/Arcane Mail|Arcane Messages|Gmail|WhatsApp|Twilio/,file)}});
test('Mail and Messages are thin shells over shared communications capabilities',async()=>{const [mail,messages,mailModule,messagesModule,registry]=await Promise.all([read('apps/mail/index.html'),read('apps/messages/index.html'),read('apps/mail/modules/MailApp.js'),read('apps/messages/modules/MessagesApp.js'),read('machine_bundles/arcane-os-machine-bundle-v0.8.4/arcane-apps.json').then(JSON.parse)]);for(const html of [mail,messages])for(const component of ['unified-inbox','conversation-view','integration-settings','theme-switcher'])assert.match(html,new RegExp(`arcane/components/${component}\\.html`));for(const source of [mailModule,messagesModule]){assert.match(source,/CommunicationAppController/);assert.doesNotMatch(source,/class Communication|innerHTML|fetch\s*\(/)}assert.match(messagesModule,/messages\.google\.com\/web/);assert.match(messagesModule,/defaultEnabled:true/);assert.deepEqual(registry.apps.mail.capabilities,['external.open','network.status.read','preferences.read','preferences.write','appearance.read','appearance.write']);assert.deepEqual(registry.apps.messages.capabilities,registry.apps.mail.capabilities.slice(1));for(const app of ['mail','messages']){const entries=await readdir(new URL(`../apps/${app}`,import.meta.url));assert(!entries.includes('components'));assert(!entries.includes('entities'))}});
test('connection settings do not solicit or persist provider secrets',async()=>{const sources=await Promise.all(['arcane/components/integration-settings.html','arcane/modules/CommunicationPreferences.js','apps/mail/modules/MailApp.js','apps/messages/modules/MessagesApp.js'].map(read));for(const source of sources)assert.doesNotMatch(source,/name=["']?(password|token|secret)|apiKey\s*:|authToken\s*:/i);assert.match(sources[0],/Passwords and API secrets are never stored here/)});
