import assert from 'node:assert/strict';
import {readFile,readdir} from 'node:fs/promises';
import test from 'node:test';
import ApiModelDatabase from '../arcane/modules/ApiModelDatabase.js';
import CalculatorEngine,{evaluateExpression} from '../arcane/modules/CalculatorEngine.js';
import GifEncoder from '../arcane/modules/GifEncoder.js';
import {parseYouTubeMedia,youtubeEmbedUrl} from '../arcane/modules/YouTubeMedia.js';
import {mapForecast} from '../arcane/modules/OpenMeteoWeatherProvider.js';
import {WeatherLocation,WeatherSnapshot} from '../arcane/entities/Weather.js';
import {validateAppRegistry} from '../machine_bundles/arcane-os-machine-bundle-v0.8.4/tools/app-packager-lib.mjs';

const read=relative=>readFile(new URL(`../${relative}`,import.meta.url),'utf8');

test('API model database fetches, parses, returns, caches, and emits neutral events',async()=>{const calls=[],events=[],details=[],cache=new Map(),model=new ApiModelDatabase({endpoint:'https://example.test/models',cache:{async get(key){return cache.get(key)},async set(key,value){cache.set(key,value)}},fetchImpl:async url=>{calls.push(url.href);return {ok:true,status:200,headers:new Headers(),async json(){return {values:[2,3]}}}},parser:(raw,{context})=>raw.values.map(value=>value*context.factor)});model.addEventListener('api-model-request',event=>{events.push(event.type);details.push(event.detail)});model.addEventListener('api-model-success',event=>events.push(event.type));const record=await model.fetch({kind:'numbers',apiKey:'private-value'},{factor:4,secret:'parser-only'});assert.deepEqual(record.value,[8,12]);assert.match(calls[0],/kind=numbers/);assert.match(calls[0],/private-value/);assert.doesNotMatch(record.endpoint,/private-value/);assert.equal(details[0].context,undefined);assert.deepEqual(events,['api-model-request','api-model-success']);assert.equal((await model.cached({kind:'numbers',apiKey:'another-value'})).value[1],12);assert.throws(()=>model.setEndpoint('file:///secret'),/HTTP or HTTPS/)});
test('calculator parses arithmetic without dynamic code execution',()=>{assert.equal(evaluateExpression('2 + 3 * 4'),14);assert.equal(evaluateExpression('2^3^2'),512);assert.equal(evaluateExpression('sqrt(81) + abs(-2)'),11);assert(Math.abs(evaluateExpression('sin(pi / 2)')-1)<1e-12);assert.throws(()=>evaluateExpression('2/0'),/zero/);assert.throws(()=>evaluateExpression('globalThis.alert(1)'),/Unknown function|Unexpected/);const engine=new CalculatorEngine();assert.equal(engine.calculate('10%3').result,1)});
test('YouTube media locator accepts videos and playlists and rejects other hosts',()=>{assert.deepEqual(parseYouTubeMedia('https://youtu.be/M7lc1UVf-VE'),{type:'video',id:'M7lc1UVf-VE',playlist:''});assert.deepEqual(parseYouTubeMedia('https://music.youtube.com/watch?v=M7lc1UVf-VE&list=PLC77007E23FF423C6'),{type:'video',id:'M7lc1UVf-VE',playlist:'PLC77007E23FF423C6'});assert.match(youtubeEmbedUrl('https://youtube.com/playlist?list=PLC77007E23FF423C6'),/^https:\/\/www\.youtube-nocookie\.com\/embed/);assert.throws(()=>parseYouTubeMedia('https://example.com/video'),/Only YouTube/)});
test('GIF encoder creates a GIF89a animation from bounded image frames',async()=>{const encoder=new GifEncoder(2,2),data=new Uint8ClampedArray([255,0,0,255,0,255,0,255,0,0,255,255,255,255,255,255]);encoder.addFrame({width:2,height:2,data},{delay:100});encoder.addFrame({width:2,height:2,data},{delay:100});const bytes=new Uint8Array(await encoder.encode().arrayBuffer());assert.equal(new TextDecoder().decode(bytes.slice(0,6)),'GIF89a');assert.equal(bytes.at(-1),0x3b);assert(bytes.length>800)});
test('Open-Meteo mapping produces provider-neutral weather records',()=>{const location=new WeatherLocation({id:'x',name:'Example',latitude:1,longitude:2});const snapshot=mapForecast({current:{time:'2026-07-13T12:00:00Z',temperature_2m:72,apparent_temperature:70,relative_humidity_2m:50,precipitation:0,weather_code:1,wind_speed_10m:5,is_day:1},current_units:{temperature_2m:'°F',wind_speed_10m:'mph'},daily:{time:['2026-07-13'],weather_code:[1],temperature_2m_max:[75],temperature_2m_min:[60],precipitation_probability_max:[10],sunrise:['2026-07-13T05:30:00Z'],sunset:['2026-07-13T20:30:00Z']},daily_units:{temperature_2m_max:'°F'}},location);assert(snapshot instanceof WeatherSnapshot);assert.equal(snapshot.location.name,'Example');assert.equal(snapshot.daily[0].temperatureMax,75)});
test('new utility components are reusable, themed, accessible, and syntactically valid',async()=>{for(const file of ['web-navigator.html','media-embed.html','calculator.html','screen-capture.html','weather-widget.html']){const html=await read(`arcane/components/${file}`),script=html.match(/<script type="module">([\s\S]*?)<\/script>/)?.[1],AsyncFunction=Object.getPrototypeOf(async function(){}).constructor;assert.match(html,/arcane\/css\/theme\.css/);assert.match(html,/arcane\/css\/primitives\.css/);assert.ok(script,file);assert.doesNotThrow(()=>new AsyncFunction(script),file);assert.doesNotMatch(html,/apps\//,file)}});
test('seven utility apps are thin themed shells with correct CSS order',async()=>{const apps=['browser','youtube','youtube-music','markdown','calculator','capture','weather'];for(const app of apps){const html=await read(`apps/${app}/index.html`),entries=await readdir(new URL(`../apps/${app}`,import.meta.url));const theme=html.indexOf('arcane/css/theme.css'),primitives=html.indexOf('arcane/css/primitives.css'),appStyle=html.indexOf(`apps/${app}/${app}.css`);assert(theme>=0&&primitives>theme&&appStyle>primitives,`${app} CSS order`);assert.match(html,/arcane\/modules\/ThemeBootstrap\.js/);assert.match(html,/arcane\/components\/theme-switcher\.html/);assert(!entries.includes('components'),`${app} has no app-local components`);assert(!entries.includes('entities'),`${app} has no app-local entities`)}});
test('machine registry explicitly gates display capture and embedded frames',async()=>{const raw=JSON.parse(await read('machine_bundles/arcane-os-machine-bundle-v0.8.4/arcane-apps.json')),registry=validateAppRegistry(raw);assert.deepEqual(registry.apps.capture.capabilities,['appearance.read','appearance.write','media.display']);assert.deepEqual(registry.apps.browser.security.frameOrigins,['https:']);assert.deepEqual(registry.apps.youtube.security.frameOrigins,['https://www.youtube-nocookie.com']);assert(!registry.apps.weather.capabilities.includes('web.embed'));const copy=structuredClone(raw);copy.apps.weather.security.frameOrigins=['https://example.com'];assert.throws(()=>validateAppRegistry(copy),/requires the web\.embed capability/)});
test('new utility styles use Arcane tokens and RGB notation rather than hexadecimal colors',async()=>{const files=['arcane/css/utility-workspace.css','apps/browser/browser.css','apps/youtube/youtube.css','apps/youtube-music/youtube-music.css','apps/markdown/markdown.css','apps/calculator/calculator.css','apps/capture/capture.css','apps/weather/weather.css'];for(const file of files){const css=await read(file);assert.doesNotMatch(css,/#[0-9a-f]{3,8}\b/i,file)}});
